import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./pages/common/Header";
import Footer from "./pages/common/Footer";
import MainLayout from "./MainLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainLayout>
          <Header />
          {children}
          <Footer />
        </MainLayout>
      </body>
    </html>
  );
}
